# Optional: Docker Compose for Qdrant (if using Docker)
# Usage: docker-compose -f docker-compose.qdrant.yml up -d
version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: payroll-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333

volumes:
  qdrant_storage: